### PR TITLE
Some improvements for de locale by OE5JFE

### PR DESCRIPTION
**Pull request by DocViper666**
- All Versions "Dein Log" changed to "Mein Log" (I want to see my log and not your log)
- "Ewige" Bestenlisten changed to Bestenlisten. That is just not needed imho.
- Additions to CSV/TSV section
- Whitespaces matched with source
- Startpage entries simplified

### CODE REVIEW

**Comment by vk3arr** [comment]
Hi Matt,

Thanks for the pull request.  Given I'm no expert on German, I'll also ask Pom @dg7acf to have a look and comment before I merge with master.  I don't mean to cause offence by doing so, just getting a second pair of eyes to look over the changes to see they make sense :)

Cheers,
Andrew

**Comment by DocViper666** [comment]
That is perfecty okay. Btw. it's Joe, OE5JFE

**Comment by vk3arr** [comment]
Sorry Joe.  Don't mind me, I'm an idiot.

**Comment by dg7acf** [comment]
I wouldn't be very happy with his version. Most of the proposes only have a different style that is not mine, leave out more of the genuine text or add facts to the text that haven't been in the English version.


> All Versions "Dein Log" changed to "Mein Log" (I want to see my log and not your log)

Yes, the computer now says "Your log" (Dein Log), i.e. theirs from the user's perspective. Before the computer said "My log", so that would have been the computer's log. To german thinking, it is more logical now.

> "Ewige" Bestenlisten changed to Bestenlisten. That is just not needed imho.

"Ewige Bestenliste" is a well-known german term referring to a table that is cumulative and neverending. Unlike the Rugby League where the team with the most points win at the end of the season and all start from nil into the new season a few weeks later.

>  Additions to CSV/TSV section

... that weren't there before.

>  Startpage entries simplified

... by leaving genuine English text.

I worked as a radio and TV writer and presenter for 15 years and still think that I can handle german quite well. To my mind, this version is no improvement and it's full of typos. 

Ahoi
Pom

**Comment by DocViper666** [comment]
Hard to argue against personal writing style. 
I still like the more personal "Mein xyz Log". Ich will mein Log sehen (deswegen klicke ich hier).

Leaving genuine text to adopt it to current (Newsotadata features, 2019 software) circumstances should probably be handled differently. First let's update/improve the English and then the other languages.
+1

Okay, I found some typos going over it again: +1
The beauty of GitHub is that it is supposed to collaboratively improve things. It's not always black or white.

Anyway I guess I'am out of the German language topic. Personally I will stick with the English version like with most software and websites.
Or I create a nimble Austrian version ;-)

73 Joe

**Comment by vk3arr** [comment]
OK, so I guess I'll leave the changes as is for now.  

I agree with both your points: the translated text should match the English text, other than minor contextual changes (eg, "please" doesn't exist as a concept in Korean, other than servile begging), but I also agree the English text is probably overdue for an update as well.  

> Anyway I guess I'am out of the German language topic

Don't take constructive criticism as a reason to abandon any collaboration.  It is much appreciated, and I think it's wise too to consider potential updates for the English text.  Likewise, Pom, please don't consider these requests as suggesting your translation is wrong, but as opening points for discussion.

Thanks both for your contributions so far.

Cheers,
Andrew
@DocViper666 @dg7acf

**Pull request closed without merging**
