### PR TITLE
Added pt_BR translation

### PR DESCRIPTION
**Pull request by dbahiense**
This is the Brazilian Portuguese locale translation.
Could also be used for all Portuguese variants while the European Portuguese locale is not updated.

### CODE REVIEW

**Comment by vk3arr** [comment]
Hi Douglas, 

Thanks for this.  There's only issue unfortunately, which is all your translations need to be surrounded by &lt;target&gt; tags, rather than the &lt;source> tags you've used, eg:

&lt;source>Hello&lt;/source>
&lt;target>こんにちは&lt;/target

**Comment by dbahiense** [comment]
Ups... my bad!
I'll change it... sorry.

**Comment by dbahiense** [comment]
Hi Andrew!
It is now correct.
Do I need to do a new pull request or you can push it without problems?

**Comment by vk3arr** [comment]
Hi Douglas, merged clean.  I'll push it live later today.  Thanks for the contribution!

**Comment by vk3arr** [comment]
I spoke a fraction too soon, but the reason is entirely my fault.  I suspect you used the original messages.pt.xlf file, which I hadn't updated with new strings.  I've merged your changes, and then merged the updated messages in messages.pt_BR.xlf, which includes &lt;target> tags now.  You can search for 'state="new"' to find the new missing strings.

The PT-BR translation works well, but for the missing translations.  I can either push it half-translated now, or wait for the additional translations.  I'll take whatever option you want.

**Comment by dbahiense** [comment]
Hi Andrew,



I'll translate the aditional terms and push it.

----

Douglas B. P. da Silva, Obl. OSB



+55 (24) 2249 0200

+55 (24) 992 534 968


+49 (89) 2033 4482
+49 (0) 152 3358 1591

mailto:douglas@rohling.com.br?subject=Assinatura

http://www.rohling.com.br




---- Ativado Ter, 25 ago 2020 22:13:40 -0300 vk3arr <notifications@github.com> escreveu ----




I spoke a fraction too soon, but the reason is entirely my fault.  I suspect you used the original messages.pt.xlf file, which I hadn't updated with new strings.  I've merged your changes, and then merged the updated messages in messages.pt_BR.xlf, which includes <target> tags now.  You can search for 'state="new"' to find the new missing strings.

The PT-BR translation works well, but for the missing translations.  I can either push it half-translated now, or wait for the additional translations.  I'll take whatever option you want.

**Pull request merged**
